### ISSUE TITLE
quietly fails (returns no results) when everything GUI is not running

### ISSUE THREAD

**Issue by gfody** [powercode/PSEverything#1]
if you've configured the everything gui to not stay open, e.g.:
![options](https://cloud.githubusercontent.com/assets/1146032/21596475/8a6fc05a-d0f0-11e6-953f-95acdccf7d37.png)
..even though the service is running, the search command returns nothing.

**Comment by powercode** [comment]
I think this may be by design. The everything SDK seems to be using window messages to communicate between processes, and when you close everything's UI, there is no one processing the messages the SDK dlls is sending.

This is also causing failures when you query from a different security context (elevated vs non-elevated).

**Comment by gfody** [comment]
I see, everything's own command line utilities also don't work when the gui isn't running. Some error message instead of no results would be nice but I guess it's reasonable that PSEverything would do what they do

**Comment by powercode** [comment]
I updated to the latest SDK now, and if you run Everything as admin, PSEverything will now work both with elevated and non-elevated powershell processes.
